SPORTS_DATA_GOLF:	 2r6y652axr88qeu2ufpbz4g4
SPORTS_DATA_MLB:	 8gz4vfrja2h6gx9g4qq3n74k
SPORTS_DATA_NBA:	 eejsybfqqtaeggwm7xmmstub
SPORTS_DATA_NCAA_FOOTBALL: 9cxxrtj6zzt965ub2jd7sbss
SPORTS_DATA_NCAAMB: qavjkb6cqv78gtkj8gag5s2n
SPORTS_DATA_NFL: 44bfapvdt29h7hkya4euegtp
SPORTS_DATA_NHL: bst8emuxbbext3xghmv9y8fq